import type { BeginnerStage } from './types'

export const beginnerStages: BeginnerStage[] = [
  {
    id: 'clone-starter',
    stage: '01',
    title: 'Clone the starter kit',
    question: 'How do I clone and run the Next.js Supabase starter kit?',
    goal: 'Download the starter, install its packages, and start the local development server.',
    answer: 'Cloning creates a separate local copy of the starter repository without changing the original project on GitHub. After npm installs the required packages, npm run dev starts a private development server on your computer. The printed local URL lets you inspect the starter before making changes.',
    duration: '10-20 minutes',
    prerequisites: ['Git, Node.js, and npm pass the checks above.', 'Kimi Code is installed and you have completed /login.', 'You have a GitHub account for saving your work later.'],
    command: {
      label: 'RUN IN YOUR TERMINAL',
      value: 'git clone https://github.com/malcolmkhong/supabase-next-vercel-starter.git\ncd supabase-next-vercel-starter\nnpm install\nnpm run dev',
    },
    callout: {
      label: 'OPEN YOUR LOCAL APP',
      beforeLink: 'Open your browser and go to',
      linkLabel: 'http://localhost:3000/',
      href: 'http://localhost:3000/',
      afterLink: '.',
      description: 'This is your local development server. Any code changes you make will appear here automatically. Supabase-backed features become available after Stage 3.',
    },
    prompt: 'I cloned the starter kit and started the development server. Inspect the project without changing files. Explain what already works, identify any missing environment variables, and tell me the next safe step in simple words.',
    steps: [
      { title: 'Clone the repository', body: 'git clone downloads the starter files into a new supabase-next-vercel-starter folder.' },
      { title: 'Enter the project folder', body: 'cd changes the terminal location. Every later command must run inside this folder.' },
      { title: 'Install the packages', body: 'npm install reads package.json and downloads the exact tools the app needs.' },
      { title: 'Start local development', body: 'npm run dev starts Next.js. The public home page may open now; Supabase-backed features become usable after Stage 3 adds .env.local.' },
    ],
    expected: 'The terminal shows a local URL, the repository folder exists, and Kimi Code can explain the project without editing it.',
    checks: ['Open http://localhost:3000/ and confirm the starter page responds.', 'Confirm the terminal is still running without a red build error.', 'Run git status and confirm you have not accidentally changed starter files.'],
    commonProblems: [
      { problem: 'git or npm is not recognized.', fix: 'Install the missing tool, close the terminal, open a new terminal, and run its version check again.' },
      { problem: 'Port 3000 is already in use.', fix: 'Use the alternate URL printed by Next.js, or stop the other local server before trying again.' },
      { problem: 'Supabase environment variable error.', fix: 'The clone worked. Continue to Stage 3 to create .env.local before testing sign-in.' },
    ],
    references: [
      { label: 'Starter repository', href: 'https://github.com/malcolmkhong/supabase-next-vercel-starter' },
      { label: 'Kimi Code CLI quick start', href: 'https://www.kimi.com/code/docs/en/kimi-code-cli/guides/getting-started.html' },
      { label: 'Next.js installation', href: 'https://nextjs.org/docs/app/getting-started/installation' },
    ],
  },
  {
    id: 'workspace',
    stage: '02',
    title: 'Understand your workspace',
    question: 'Which starter-kit files should a beginner understand first?',
    goal: 'Learn the small set of files you will use and establish a safe Kimi Code work loop.',
    answer: 'You do not need to understand every starter file before building. Begin with app for pages, components for reusable interface pieces, lib/supabase for database clients, proxy.ts for session refresh, and .env.local for local configuration. Knowing these locations is enough to review Kimi Code’s proposed changes safely.',
    duration: '20-30 minutes',
    prerequisites: ['Stage 1 is complete.', 'The starter folder is open in your editor.', 'Kimi Code is running from the repository root.'],
    prompt: 'Inspect this starter kit without changing files. Explain app, components, lib/supabase, proxy.ts, package.json, and .env.example in a beginner-friendly table. Then propose one small plan for turning the starter into a project and task manager. Wait for my approval.',
    steps: [
      { title: 'Generate project context', body: 'In Kimi Code, run /init. Review the generated AGENTS.md before keeping it so future sessions know how this repository works.', code: '/init' },
      { title: 'Read the page entry point', body: 'Open app/page.tsx. Identify what appears on the public home page and which components it imports.' },
      { title: 'Find the auth boundary', body: 'Open proxy.ts and app/private/page.tsx. Ask Kimi to explain how an unsigned visitor is redirected.' },
      { title: 'Approve small changes only', body: 'For every feature, ask for a plan, review the named files, approve the change, and run the suggested test before continuing.' },
    ],
    expected: 'You can describe where pages, shared components, Supabase clients, authentication, configuration, and scripts live.',
    checks: ['Ask Kimi to name the development command and verify it matches package.json.', 'Confirm Kimi identifies the existing email/password authentication before proposing Google sign-in.', 'Confirm the proposed task-manager plan does not delete the working auth starter.'],
    commonProblems: [
      { problem: 'The explanation contains too much jargon.', fix: 'Ask Kimi to explain one folder at a time and define every unfamiliar term.' },
      { problem: 'Kimi starts editing immediately.', fix: 'Interrupt the run and repeat: inspect only, list files, propose a plan, and wait for approval.' },
    ],
    references: [
      { label: 'Kimi Code first conversation', href: 'https://www.kimi.com/code/docs/en/kimi-code-cli/guides/getting-started.html#your-first-conversation' },
      { label: 'Next.js project structure', href: 'https://nextjs.org/docs/app/getting-started/project-structure' },
    ],
  },
  {
    id: 'supabase',
    stage: '03',
    title: 'Set up Supabase',
    question: 'How do I connect the starter kit to a Supabase project?',
    goal: 'Create a Supabase project, add the public connection values locally, and confirm the starter can reach it.',
    answer: 'The starter connects to Supabase using a project URL and publishable key stored in .env.local on your computer. These values identify the correct backend but do not replace access rules. Row Level Security must still decide which project and task records each signed-in user can read or change.',
    duration: '20-30 minutes',
    prerequisites: ['Stages 1 and 2 are complete.', 'You can sign in to the Supabase Dashboard.', 'The development server can be restarted.'],
    prompt: 'Help me connect this existing Next.js starter to a new Supabase project. Inspect .env.example and the clients in lib/supabase first. Give me dashboard steps and the exact .env.local variable names. Never request or expose a secret or service-role key.',
    steps: [
      { title: 'Create the cloud project', body: 'Open the Supabase Dashboard, choose New project, select your organization and region, create a strong database password, and wait for the database to become ready.' },
      { title: 'Copy the connection values', body: 'Open the project Connect dialog. Copy the Project URL and Publishable key. Do not use a secret or service-role key in a NEXT_PUBLIC variable.' },
      { title: 'Create .env.local', body: 'Copy .env.example to .env.local and replace the placeholders. Do not commit .env.local.', code: 'NEXT_PUBLIC_SUPABASE_URL=https://YOUR_PROJECT_REF.supabase.co\nNEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=sb_publishable_YOUR_KEY' },
      { title: 'Restart and test', body: 'Stop the development server with Ctrl+C, run npm run dev again, open /login, and confirm the page loads without a missing-variable error.' },
    ],
    expected: 'The app reads both public environment variables, /login loads, and .env.local remains ignored by Git.',
    checks: ['Run git status and confirm .env.local is not listed.', 'Open http://localhost:3000/login and confirm there is no missing Supabase variable error.', 'Confirm you used a publishable key, not a secret or service-role key.'],
    commonProblems: [
      { problem: 'The old values still appear after editing .env.local.', fix: 'Restart npm run dev because Next.js reads environment variables when the server starts.' },
      { problem: 'The project URL or key is rejected.', fix: 'Copy both values again from the same Supabase project Connect dialog and remove accidental spaces or quotes.' },
    ],
    references: [
      { label: 'Supabase Next.js server-side auth', href: 'https://supabase.com/docs/guides/auth/server-side/nextjs' },
      { label: 'Supabase API keys', href: 'https://supabase.com/docs/guides/api/api-keys' },
      { label: 'Next.js environment variables', href: 'https://nextjs.org/docs/app/guides/environment-variables' },
    ],
  },
  {
    id: 'google-auth',
    stage: '04',
    title: 'Add Google sign-in',
    question: 'How do I add Google OAuth to a Next.js Supabase app?',
    goal: 'Configure Google and Supabase, add a sign-in button, and verify the complete session flow.',
    answer: 'Google OAuth connects three parts: your Google Cloud credentials, the Supabase authentication provider, and your app’s callback route. The app asks Supabase to begin sign-in, Google confirms the user’s identity, and Supabase returns the user only to an approved local or production URL.',
    duration: '30-45 minutes',
    prerequisites: ['Stage 3 connection test passes.', 'You can access Google Cloud Console.', 'You know the local and future production app URLs.'],
    prompt: 'Add Google sign-in to this existing Supabase SSR starter. Preserve the current cookie-based server client and protected route. First show me the required Google and Supabase dashboard settings, callback URLs, files you will change, and tests. Wait for approval before editing.',
    steps: [
      { title: 'Create Google OAuth credentials', body: 'In Google Cloud Console, configure the OAuth consent screen and create a Web application client. Use the Supabase callback URL shown in the Google provider settings as the authorized redirect URI.' },
      { title: 'Enable the provider', body: 'In Supabase Dashboard, open Authentication > Providers > Google. Enable it and paste the Google client ID and secret. Keep the secret in the dashboard, never in frontend code.' },
      { title: 'Allow app redirects', body: 'In Authentication > URL Configuration, set the local Site URL to http://localhost:3000 and allow the local callback path used by your app. Add the Vercel URL in Stage 8.' },
      { title: 'Build and test the flow', body: 'Ask Kimi to add a Continue with Google button, exchange the returned code for a cookie-backed session, preserve safe next paths, and show a clear error when sign-in fails.' },
    ],
    expected: 'A visitor can choose Google, return to the app as an authenticated user, refresh the protected page, and sign out.',
    checks: ['Sign in with a test Google account and open the protected page.', 'Refresh the browser and confirm the session remains.', 'Sign out and confirm the protected page redirects to /login.'],
    commonProblems: [
      { problem: 'redirect_uri_mismatch appears.', fix: 'Compare the full callback URL in Google Cloud with the callback URL shown by Supabase. Scheme, host, path, and trailing slash must match.' },
      { problem: 'Sign-in succeeds but returns to the wrong page.', fix: 'Check Supabase Site URL, allowed redirect URLs, and the redirectTo value passed by the app.' },
    ],
    references: [
      { label: 'Supabase Google login', href: 'https://supabase.com/docs/guides/auth/social-login/auth-google' },
      { label: 'Google OAuth web server guide', href: 'https://developers.google.com/identity/protocols/oauth2/web-server' },
    ],
  },
  {
    id: 'database',
    stage: '05',
    title: 'Create safe project data',
    question: 'How should projects, tasks, and Row Level Security be designed?',
    goal: 'Create durable project and task data that is private to its owner by default.',
    answer: 'Every project and task needs an owner ID connected to the signed-in user. Row Level Security must verify that ownership for every select, insert, update, and delete operation. Task policies should also confirm ownership of the parent project, preventing users from reading or moving data that belongs to someone else.',
    duration: '45-60 minutes',
    prerequisites: ['Google sign-in works.', 'You can open Supabase SQL Editor.', 'You have a second test account for privacy testing.'],
    prompt: 'Create a reviewed Supabase migration for projects and tasks. Include UUID primary keys, owner IDs linked to auth.users, timestamps, task status, priority, due date, indexes, grants when required by Data API settings, and RLS. Every policy must restrict rows to auth.uid(). UPDATE policies need USING and WITH CHECK. Show the migration and test plan before applying it.',
    steps: [
      { title: 'Define the schema', body: 'Projects need owner, name, description, and timestamps. Tasks need project, owner, title, description, status, priority, due date, and timestamps. Use constrained values for status and priority.' },
      { title: 'Create a migration', body: 'Ask Kimi to create a named migration file under supabase/migrations. Review the SQL before running it; do not paste unreviewed SQL into production.' },
      { title: 'Enable ownership policies', body: 'Enable RLS on both tables. SELECT, INSERT, UPDATE, and DELETE must check the signed-in owner. Task access must also require ownership of its parent project.' },
      { title: 'Check Data API access', body: 'New Supabase projects may not expose new public tables automatically. Review Data API settings and grant only the required privileges to authenticated users while keeping RLS enabled.' },
    ],
    expected: 'The database contains indexed projects and tasks tables with RLS enabled and ownership-safe policies for all operations.',
    checks: ['Create data as account A and confirm account B cannot read, edit, or delete it.', 'Try changing owner_id during an update and confirm the policy rejects it.', 'Confirm unauthenticated requests cannot access either table.'],
    commonProblems: [
      { problem: 'Queries return no rows without an error.', fix: 'Confirm the user is signed in and that both SELECT and UPDATE policies exist. UPDATE requires a matching SELECT policy.' },
      { problem: 'The table is inaccessible even with a correct RLS policy.', fix: 'Check the project Data API settings and required authenticated-role grants. Grants and RLS solve different parts of access control.' },
    ],
    references: [
      { label: 'Supabase Row Level Security', href: 'https://supabase.com/docs/guides/database/postgres/row-level-security' },
      { label: 'Secure the Data API', href: 'https://supabase.com/docs/guides/api/securing-your-api' },
      { label: 'Supabase database migrations', href: 'https://supabase.com/docs/guides/deployment/database-migrations' },
    ],
  },
  {
    id: 'projects-tasks',
    stage: '06',
    title: 'Build projects and tasks',
    question: 'What is the safest order for building project and task features?',
    goal: 'Build the core create, read, edit, complete, and delete actions in small testable slices.',
    answer: 'Build the data experience in small, testable steps: show projects first, then create and edit tasks, and add deletion last. Every action should validate the user’s input, display loading and error feedback, and read the saved record back from Supabase so you know the change persisted correctly.',
    duration: '60-90 minutes',
    prerequisites: ['Stage 5 privacy tests pass.', 'You have a signed-in test account.', 'You know the project and task fields.'],
    prompt: 'Build the core project and task workflow in small reviewed steps. Start with project list and creation, then task list, create, edit, complete, and delete. Use server-side ownership-safe Supabase queries, validate inputs, include loading, empty, error, and confirmation states, and add tests for each slice. Stop after each slice for review.',
    steps: [
      { title: 'Projects first', body: 'Create the empty state, project form, project list, and active-project selection. Require a short non-empty name and display useful save errors.' },
      { title: 'Add task creation', body: 'Start with title and status. Then add description, priority, and due date after the simplest save-and-refresh path works.' },
      { title: 'Edit and complete', body: 'Let users update task details and mark a task complete. Disable duplicate submissions and keep the form values when a save fails.' },
      { title: 'Delete carefully', body: 'Use a confirmation dialog that names the project or task. After deletion, show the correct empty state and update the active selection.' },
    ],
    expected: 'A signed-in user can create, read, edit, complete, and delete their own projects and tasks with clear feedback.',
    checks: ['Create a project and task, refresh, and confirm both remain.', 'Submit an empty title and confirm a plain-language validation message appears.', 'Force a failed save and confirm the interface explains the failure without losing entered text.', 'Delete a task and confirm it stays deleted after refresh.'],
    commonProblems: [
      { problem: 'The interface changes but the database does not.', fix: 'Refresh from Supabase after the mutation and surface the returned error instead of assuming the optimistic change succeeded.' },
      { problem: 'A form submits twice.', fix: 'Disable the submit button while saving and make the server action validate every request.' },
    ],
    references: [
      { label: 'Next.js forms and Server Actions', href: 'https://nextjs.org/docs/app/guides/forms' },
      { label: 'Supabase JavaScript insert data', href: 'https://supabase.com/docs/reference/javascript/insert' },
      { label: 'WAI dialog pattern', href: 'https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/' },
    ],
  },
  {
    id: 'dashboard',
    stage: '07',
    title: 'Add dashboard, search, and filters',
    question: 'How do I make a task dashboard useful and accessible?',
    goal: 'Help users understand their workload and find tasks without losing the underlying saved data.',
    answer: 'A useful dashboard summarizes the signed-in user’s real task data before offering search, status, priority, and due-date filters. The controls should work together predictably, show an understandable empty state when nothing matches, and include a clear reset action. Keyboard and mobile users must be able to reach every filter.',
    duration: '60-90 minutes',
    prerequisites: ['Project and task CRUD works after refresh.', 'You have sample tasks with different statuses, priorities, and dates.', 'Mobile and keyboard testing are available.'],
    prompt: 'Add a responsive task dashboard. Include summary cards, search, status, priority, and due-date filters, clear-all, result count, loading, empty, no-results, and error states. Define filter behavior before coding, keep labels beginner-friendly, and test combinations plus keyboard use. Preserve the existing database and auth flow.',
    steps: [
      { title: 'Define the filter rules', body: 'Search matches task title and description. Status and priority use exact values. Due date separates overdue, due soon, and no due date. All active filters combine.' },
      { title: 'Build summary cards', body: 'Show total, active, completed, and overdue counts calculated from the same visible task data. Give each number a clear label.' },
      { title: 'Handle every state', body: 'Differentiate first-use empty state, no search results, loading, and a real server error. Every state should tell the user what to do next.' },
      { title: 'Test mobile and keyboard use', body: 'Use visible labels, logical focus order, large touch targets, and a clear reset action. Do not rely on color alone for status or priority.' },
    ],
    expected: 'Users can understand the workload, combine filters, reset them, and use the dashboard on phone or desktop.',
    checks: ['Test search and each filter separately, then test at least three combinations.', 'Confirm summary numbers match the visible task data.', 'Use only the keyboard to search, change filters, clear them, and open a task.', 'Check the layout at 375px width without horizontal scrolling.'],
    commonProblems: [
      { problem: 'Filters show stale results after editing a task.', fix: 'Use one shared source of task data and recompute summaries and filtered results after every successful mutation.' },
      { problem: 'No-results looks like a server failure.', fix: 'Use separate messages and actions for an empty project, a filtered result of zero, and a failed request.' },
    ],
    references: [
      { label: 'React accessibility', href: 'https://react.dev/learn' },
      { label: 'WCAG input purposes and labels', href: 'https://www.w3.org/WAI/WCAG22/Understanding/labels-or-instructions.html' },
    ],
  },
  {
    id: 'deploy',
    stage: '08',
    title: 'Deploy your app',
    question: 'How do I finish the Kanban board and deploy safely to Vercel?',
    goal: 'Add a resilient Kanban view, verify the complete app, and publish it with production auth configuration.',
    answer: 'Deployment is complete only when the production app can sign in through the correct callback URL, protect private data, create and move tasks, preserve changes after refresh, and work on a phone. A successful build is only the first check; repeat the full user journey on the deployed Vercel address.',
    duration: '60-90 minutes',
    prerequisites: ['Stages 1-7 pass their checks.', 'The code is pushed to your own GitHub repository.', 'You have access to Vercel and the Supabase project settings.'],
    prompt: 'Finish and deploy this app. Add an accessible Kanban view whose status changes persist to Supabase and roll back with a clear message on failure. Test keyboard and mobile behavior. Then prepare a Vercel deployment, list the required environment variables and production OAuth redirect URLs, run tests and a production build, and wait for my approval before deployment.',
    steps: [
      { title: 'Finish Kanban safely', body: 'Provide To do, In progress, and Done columns. Support a keyboard-accessible status control even if drag-and-drop is available. Persist first or roll back the card when saving fails.' },
      { title: 'Run the release checks', body: 'Run lint, tests, and npm run build. Fix the first real error, rerun the failed check, and then rerun the full set.' },
      { title: 'Deploy with environment values', body: 'Import the GitHub repository into Vercel and add the Supabase URL and publishable key to Production and Preview environments. Never add a secret key to NEXT_PUBLIC variables.' },
      { title: 'Finish production OAuth', body: 'Add the final Vercel domain to Supabase allowed redirect URLs and any required Google OAuth origins. Test sign-in from the deployed URL, not only localhost.' },
    ],
    expected: 'The live app signs users in, protects their data, saves Kanban status changes, handles failures, and works at phone and desktop widths.',
    checks: ['Open the production URL in a private browser window and complete Google sign-in.', 'Create a task, move it, refresh, and confirm the status persists.', 'Confirm a second account cannot access the first account data.', 'Check keyboard operation, 375px layout, loading states, and error messages.', 'Confirm no secret or .env.local file exists in GitHub or the browser bundle.'],
    commonProblems: [
      { problem: 'Local sign-in works but production sign-in fails.', fix: 'Add the exact production domain and callback path to Supabase URL Configuration and Google OAuth settings, then redeploy if environment values changed.' },
      { problem: 'Vercel builds but the page fails at runtime.', fix: 'Check Vercel runtime logs and confirm both public Supabase variables exist in the correct environment.' },
      { problem: 'A moved card returns after refresh.', fix: 'Treat the Supabase update as the source of truth and display or roll back failures instead of leaving an unsaved visual state.' },
    ],
    references: [
      { label: 'Vercel Next.js deployment', href: 'https://vercel.com/docs/frameworks/full-stack/nextjs' },
      { label: 'Vercel environment variables', href: 'https://vercel.com/docs/environment-variables' },
      { label: 'Supabase redirect URLs', href: 'https://supabase.com/docs/guides/auth/redirect-urls' },
      { label: 'WAI drag-and-drop guidance', href: 'https://www.w3.org/WAI/ARIA/apg/practices/keyboard-interface/' },
    ],
  },
]
