export const comingSoonContent = {
  status: 'In development',
  headingSuffix: 'Experience — Coming Soon',
  supportingDescription: 'We are currently preparing this experience. You can explore the available pages or try Kimi directly while development continues.',
  invitationAction: 'Try Kimi with My Invitation Link',
  invitationDisclosure: 'This page participates in the Kimi Viral Referral Program. I may receive referral rewards when you register through this invitation link.',
  exploreAction: 'Explore Available Pages',
  availablePagesLabel: 'Available pages',
  previewDisclosure: 'Interface preview · controls are simulated',
  desktop: {
    applicationName: 'Agent Workspace Preview',
    workspaceTab: 'Workspace',
    chatTab: 'Chat',
    newChat: 'New chat',
    sidebarItems: ['Tools', 'Automations', 'Research', 'Documents', 'Web projects'],
    history: 'Chats',
    placeholderConversations: ['Learning path review', 'Project planning notes', 'Tool setup questions'],
    inviteAction: 'Invite to Earn',
    inviteSupportingText: 'Share Kimi and receive referral rewards',
    previewAccount: 'Preview account',
    workspaceLabel: 'Agent workspace',
    upgradeAction: 'Upgrade Your Plan',
    assistantName: 'Guide agent',
    responseLabel: 'Simulated agent response',
    states: ['Thinking', 'Generating text', 'Streaming response', 'Complete'],
    requestPrefix: 'Prepare a clear, practical',
    requestSuffix: 'learning experience and explain what will be included.',
    responsePrefix: 'Done — I prepared the first outline for the',
    responseSuffix: 'experience. It will guide beginners through each outcome with plain-language explanations, practical examples, and clear checks.',
    composerEyebrow: 'Development preview',
    inputLabel: 'Message input preview',
    inputPlaceholder: 'Ask the agent about this upcoming experience',
    sendLabel: 'Send message — unavailable while in development',
    modelLabel: 'Preview model',
    toolChips: ['Plan', 'Research', 'Build', 'Review'],
  },
} as const
